version: "3.9"

services:
  # keeper services
  keeper:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: keeper
    container_name: keeper
    restart: always
    volumes:
      - ..:/app
    env_file:
      - .env
    entrypoint: [ "python" ]
    command: [ "./src/main.py" ]
